### GET /
GET http://localhost:3000/

### GET /user/:id
GET http://localhost:3000/user/42

### GET с query
GET http://localhost:3000/search?name=Даша&age=18

### POST
POST http://localhost:3000/post
Content-Type: application/json

{
  "name": "Лёша"
}

### PUT
PUT http://localhost:3000/put
Content-Type: application/json

{
  "updated": true
}

### PATCH
PATCH http://localhost:3000/patch
Content-Type: application/json

{
  "key": "значение"
}

### DELETE
DELETE http://localhost:3000/delete
